# Generated by Django 5.0.4 on 2024-06-07 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='livro_id',
            new_name='livro_titulo',
        ),
    ]
