# Generated by Django 5.0.4 on 2024-06-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0007_alter_livro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
